version: '3'

services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: consultation
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306